### ISSUE TITLE
Update servers to latest Kubernetes

### ISSUE THREAD

**Issue by BobyMCbobs** [ii/infra.old#11]

**Comment by riaankleinhans** [comment]
- What is the estimated time for the task?
- Any risks for downtime?

**Comment by BobyMCbobs** [comment]
> * What is the estimated time for the task?
> 
>     * Any risks for downtime?

Allocate a morning to it and expect some downtime

**Comment by riaankleinhans** [comment]
Pair on it with @zachmandeville tomorrow, using the "Lessons learned" and documentation from the last Mattermost update.
Please update documentation as new things emerge related the to K8s update.

**Comment by hh** [comment]
I’d prefer to put this off til after KubeCon

**Comment by BobyMCbobs** [comment]
> I’d prefer to put this off til after KubeCon

@hh, I think it would be highly valuable to at least plan it given the space between tasks. I can pair with @zachmandeville on it.
